sudo: required
services:
  - docker

before_install:
  - docker build -t raghav141988/react-test -f ./client/DockerFile.dev ./client

script:
  - docker run raghav141988/react-test npm test -- --coverage

after_success:
  - docker build -t raghav141988/multi-client ./client
  - docker build -t raghav141988/multi-nginx ./ngnix
  - docker build -t raghav141988/multi-server ./server
  - docker build -t raghav141988/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push raghav141988/multi-client
  - docker push raghav141988/multi-nginx
  - docker push raghav141988/multi-server
  - docker push raghav141988/multi-worker

deploy:
 provider: elasticbeanstalk
 region:  us-east-1
 app: multi-docker
 env: MultiDocker-env
 bucket_name: elasticbeanstalk-us-east-1-175709978647
 bucket_path: docker-multi
 on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: 
 secure: $AWS_SECRET_KEY

  